### ISSUE TITLE
Error when uploading a random photo 

### ISSUE THREAD

**Issue by RusseII** [pomkos/money_requesting#10]
![Screenshot_20201228-101414](https://user-images.githubusercontent.com/15036618/103224344-86c24c80-48f5-11eb-845f-75f4d107ef9a.png)

**Comment by pomkos** [comment]
Hi Russell,

This is great to know, however without the full error itself it's hard to see whats going on. I know this is your first issues submission so no worries!! Next time though, try to capture the full error, including the "line 26" stuff. May have to straight up copy-paste it.

**Comment by pomkos** [comment]
Added message of only supporting doordash
