### ISSUE TITLE
Let user select region of image to OCR, via bounding box

### ISSUE THREAD

**Issue by pomkos** [pomkos/money_requesting#27]
See `user_ocr` branch

Need to look up how, but would greatly simplify OCR.

**Comment by pomkos** [comment]
Streamlit component that could be of use:

https://github.com/rjtavares/BirdsPyView

**Comment by pomkos** [comment]
Current progress: user able to select parts of image. I just need to extract those parts using the returned coordinates.

Maybe with opencv? https://www.codementor.io/@innat_2k14/extract-a-particular-object-from-images-using-opencv-in-python-jfogyig5u

![image](https://user-images.githubusercontent.com/8731022/104128338-0fe57480-5335-11eb-8880-ac38e9f03315.png)

**Comment by Namaskar-1F64F** [comment]
Would it make more sense to have everything added and select after the fact? Selecting the area of items does make sense, but per-person might not.

**Comment by pomkos** [comment]
> Would it make more sense to have everything added and select after the fact? Selecting the area of items does make sense, but per-person might not.

Problem is that when I OCR, the strings and prices get shown out of order.  So youd have str1 str2 price1 str3 price3 price2 or something like that.

Right now im working on select per person -> crop each selection -> OCR each crop -> return prices per person.

**Comment by Namaskar-1F64F** [comment]
What about disjointed purchases on the same receipt?

**Comment by pomkos** [comment]
> What about disjointed purchases on the same receipt?

Thats accounted for with the colored boxes. So in example image above you have two black boxes, same shade. So then I can just crop those two, OCR, and merge.

**Comment by Namaskar-1F64F** [comment]
I don't see how those boxes would solve the problem of strings returning out of order. will there not be the same problem?

**Comment by pomkos** [comment]
> I don't see how those boxes would solve the problem of strings returning out of order. will there not be the same problem?

Well since everything in the boxes is assigned to the users already, I can just sum the prices up.

So red_box = [str, str, str, price, str, price, price, price], get rid of strings, sum prices. Done. Doesn't matter that I can't detect which string belongs to which price, since I'm not doing an itemized thing.

This is all in theory though. Last time I used just pytesseract and an entire receipt and it was all out of order (see `beta_image_rec.py` in apps folder. Its a mess, lots of rigid if-then statements). Working on the images as chunks should make it easier, at the very least we'll know which price belongs to which person right?

**Comment by pomkos** [comment]
Current progress:

cropped image using user input, all in buffer no saving.

![image](https://user-images.githubusercontent.com/8731022/104135580-4afc9d80-535f-11eb-99e7-87a1759e4fe4.png)

**Comment by pomkos** [comment]
Current progress:

Image cropped with OpenCV using user input (from streamlit canvas), then OCR using pytesseract.

![image](https://user-images.githubusercontent.com/8731022/104135976-3caf8100-5361-11eb-9554-bbf6ec3dae4f.png)

**Comment by pomkos** [comment]
Second box. 

![image](https://user-images.githubusercontent.com/8731022/104136015-8e580b80-5361-11eb-9ce0-9df2cb416a1e.png)

**Comment by Namaskar-1F64F** [comment]
Call me radical but can't you, er, highlight the text? 
<img width="347" alt="image" src="https://user-images.githubusercontent.com/7458951/104136123-e723a600-5359-11eb-9754-3f8d108bd3ad.png">

**Comment by pomkos** [comment]
heretic!!

**Comment by pomkos** [comment]
lol yeah good idea. I could just have them cp the whole receipt in a text box and work our magic.

I wanna expand to groceries tho, thats what the ocr is for

**Comment by pomkos** [comment]
prices found and voila

![image](https://user-images.githubusercontent.com/8731022/104136395-d2e4a680-5363-11eb-836d-60ea70b62c1b.png)

**Comment by pomkos** [comment]
Will not detect numbers in receipts

![image](https://user-images.githubusercontent.com/8731022/104136450-29ea7b80-5364-11eb-83da-0c16e1a01604.png)

**Comment by Namaskar-1F64F** [comment]
needs more machine learning

**Comment by pomkos** [comment]
OCR is unreliable on actual receipts (unless we use [mindee](https://mindee.com/)

![image](https://user-images.githubusercontent.com/8731022/104137225-3fae6f80-5369-11eb-9482-e737fbfaa16f.png)

**Comment by pomkos** [comment]
update: implemented @SvenWritesCode suggestion months ago, users now just copy paste the doordash/ubereats receipt. No OCR involved, and fast UX
